testing new help setup

diff --git a/abs b/abs
--- a/abs
+++ b/abs
@@ -1,36 +1,11 @@
 #!/bin/bash
-set -e
+#set -e
 
-source /etc/abs/misc/.bashFormatting
+source /etc/abs/misc/
 
-if [[ $1 == "help" ]]; then
-	echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
-	echo "Currently abs only has two options besides help: ${fgCyan}custom${txReset} or ${fgCyan}xero${txReset}."
-	echo "Read below for a brief description of each."
-	echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
-	echo "${txBold}custom${txReset}"
-	echo "The custom option is for the building of ${txBold}any${txReset} ${txUnderline}archiso${txReset} profile you may be working on."
-	echo "${txUnderline}It is not tied to or dependent on any arch iso or distribution${txReset}."
-	echo "This option is flexible and once again supports the building of basically any archiso profile you provide."
-	echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
-	echo "${txBold}xero${txReset}"
-	echo "The xero option is dedicated to the build of ${fgCyan}XeroLinux${txReset} using the the ${txUnderline}xero_iso git repo${txReset} as its source."
-	echo "This option will ask you if you need to clone the xero_iso git repo or ask you if you have already done so."
-	echo "If you tell abs to clone the xero_iso git repo for you it will do so and place it in your ${txUnderline}home directory${txReset}."
-	echo "The home directory is chosen so that you can easily move the cloned xero_iso build repo directory wherever you desire if need be."
-	echo "In the future I may make abs smart enough to ask where you want the cloned repo to end up and clone to your chosen destination."
-	echo "If you tell abs that you have already cloned the xero_iso git repo, abs will look for the xero profile."
-	echo "If abs cannot find the xero profile in the directory it's been called, abs will ${fgRed}exit${txReset} and ask that you ${txUnderline}cd to the cloned xero_iso repo and call abs again${txReset}."
-	echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
-#	echo "${txBold}last-error${txReset}"
-#	echo "Adding this option to abs will print last exit/err code abs set when last ran."
-#	echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
-	echo "${txBold}Passing options to abs in terminal${txReset}"
-	echo "abs can also be called with either of these options directly from terminal"
-	echo "If abs is called with the xero option however, abs will ask you if you need to git clone the xero_iso build repo or if you have already"
-	echo "Once again, if abs is told you've already cloned the xero_iso build repo and it cannot find the xerolinux profile it will exit and ask to be called in the cloned repo directory."
-	echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
-elif [[ $1 == "custom" || $1 == "Custom" || $1 == "CUSTOM" ]]; then
+if [[ $1 == "help" || $1 == "-help" || $1 == "-h" || $1 == "-H" ]]; then
+	help
+elif [[ $1 == "custom" || $1 == "Custom" || $1 == "CUSTOM" || $1 == "-c" || $1 == "-C" ]]; then
 	echo "Oki, let's get ready to build a custom iso using a user provided profile."
 	read -p "What is the name of the archiso profile abs will be building your iso with? : " archisoProfile
 	echo
@@ -38,50 +13,47 @@ elif [[ $1 == "custom" || $1 == "Custom" || $1 == "CUSTOM" ]]; then
 	if [[ ! -d $archisoProfile ]]; then
 		echo "Couldn't find the archiso profile you provided in the current directory."
 		echo "Please change to the proper directory and call abs once more."
-#		sed -i '/lastErr/c lastErr=$err1' /etc/abs/misc/lastErr
-		exit 1
+#		exit 1
 	else
 		echo "abs found your archiso profile. abs will now begin your iso's build process."
 		/etc/abs/misc/options/custom
 	fi
-elif [[ $1 == "xero" || $1 == "Xero" || $1 == "XERO" || $1 == "xerolinux" || $1 == "XeroLinux" || $1 == "Xerolinux" || $1 == "xeroLinux" ]]; then
+elif [[ $1 == "xero" || $1 == "Xero" || $1 == "XERO" || $1 == "xerolinux" || $1 == "XeroLinux" || $1 == "Xerolinux" || $1 == "xeroLinux" || $1 == "-x" || $1 == "-X" ]]; then
 	echo "Oki, let's get ready to build a xero iso from the current up to date git build repo."
 	echo
 	echo "Scanning for xerolinux profile."
 	if [[ ! -d xerolinux ]]; then
 		echo "Couldn't find the xerolinux profile in the current directory."
 		echo "Please change to the proper directory and call abs once more."
-#		sed -i '/lastErr/c lastErr=$err2' /etc/abs/misc/lastErr
-		exit 1
+#		exit 1
 	else
 		echo "abs found the xerolinux profile. abs will now begin the xero build process." && sleep 1.7
 		/etc/abs/misc/options/xero
-		exit 1
+#		exit 1
 	fi
-#elif [[ $1 == "last-error" ]]; then
-#	cat /etc/abs/misc/lastErr
+elif [[ -n $1 ]]; then
+	echo "Sorry, abs does not recognize this option. Run ${fgCyan}abs -help${txReset} for a list of accepted options and their brief descriptions."
 else
-#	echo "Sorry, abs does not recognize this option. Run ${fgCyan}abs help${txReset} for a list of accepted options and their brief descriptions."
 	read -p "Are you looking to build a ${fgCyan}${txUnderline}custom${txReset} iso or ${fgCyan}${txUnderline}xero${txReset} iso? or do you need ${fgPurple}help${txReset}? " answer
 	echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
 
 	finished='0'
 	while [ finished != 1 ]; do
 	case $answer in
-		custom | Custom | CUSTOM )
+		custom | Custom | CUSTOM | -C | -c )
 			echo "Oki, building ${fgCyan}custom${txReset} iso"
 			finished='1'
 			bash /etc/abs/misc/options/custom
-			exit 1
-#			sed '3d' /etc/abs/misc/lastErr && echo \$err0 > /etc/abs/misc/lastErr
+#			exit 1
 			;;
-		xero | XERO | xerolinux | XeroLinux | Xerolinux | xeroLinux | XEROLINUX )
+		xero | XERO | xerolinux | XeroLinux | Xerolinux | xeroLinux | XEROLINUX | -x | -X )
 			echo "Oki, building ${fgCyan}xerolinux${txReset} iso"
 			finished='1'
 			bash /etc/abs/misc/options/xero
-			exit 1
-#			sed '3d' /etc/abs/misc/lastErr && echo \$err0 > /etc/abs/misc/lastErr
+#			exit 1
 			;;
+		help | -h | -H | HELP | help )
+			
 		* )
 			echo "Not a valid abs option. Enter ${fgCyan}${txUnderline}custom${txReset} or ${fgCyan}${txUnderline}xero${txReset}"
 			echo "Additionally you can run ${fgCyan}abs help${txReset} for abs options and descriptions."
@@ -91,3 +63,8 @@ else
 	done
 fi
 
+# Functionality for the future potentially
+# Error catching
+#	echo "${txBold}last-error${txReset}"
+#	echo "Adding this option to abs will print last exit/err code abs set when last ran."
+#	echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
