creater error code list, adding error catching, created options that can passed to abs in terminal, basically a full abs rewrite, more changes than i can remember

diff --git a/misc/options/custom b/misc/options/custom
--- a/misc/options/custom
+++ b/misc/options/custom
@@ -3,21 +3,30 @@
 # Written by Keyaedisa
 # Website in the works
 
-#source "$(dirname "${BASH_SOURCE[0]}")/misc/.bashFormatting"
 source /etc/misc/.bashFormatting
+
+trap_ctrlc() {
+    echo "Ctrl-C detected. Setting lastErr to Code 5"
+    sed '$d' /etc/abs/misc/lastErr && echo \$err5 > /etc/abs/misc/lastErr
+    exit 5
+}
+
+trap "trap_ctrlc" 2
 
 checkSudo() {
     if [[ ${UID} -eq 0 ]]; then
         echo "Must ${txBold}${fgRed}NOT${txReset} run abs as root!"
         echo "Exiting now!"
-        exit 1
+        sed '$d' /etc/abs/misc/lastErr && echo \$err6 > /etc/abs/misc/lastErr
+        exit 6
     fi
 }
 
 checkInternetConnection() {
 	ping -c 1 -q xerolinux.xyz >&/dev/null; if [[ $? != 0 ]]; then
 	echo "${fgRed}Not connected to the internet${txReset}! Fix that and try again."
-	exit 1
+	sed '$d' /etc/abs/misc/lastErr && echo \$err7 > /etc/abs/misc/lastErr
+	exit 7
 	fi
 }
 
@@ -31,19 +40,21 @@ isArchisoUpToDate () {
 		echo "Latest archiso check ${fgRed}failed${txReset}!"
 		echo "Exiting now!"
 		sudo rm stfu.txt
-		exit 1
+		sed '$d' /etc/abs/misc/lastErr && echo \$err8 > /etc/abs/misc/lastErr
+		exit 8
 	fi
 }
 
 checkSudo
 
 echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
-echo "${fgCyan}Step 1${txReset}: Getting ready to ${fgCyan}build${txReset}!"
+echo "${fgCyan}Step 1${txReset}: Getting ready to build your ${fgCyan}custom${txReset} iso!"
 echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
 read -p "Please enter the name of your ${fgCyan}archiso${txReset} profile: " archisoProfile
 if [[ ! -d $archisoProfile ]]; then
 	echo "Couldn't find ${fgRed}${archisoProfile}${txReset}! Are you sure you're in the correct directory?"
-	exit
+	sed '$d' /etc/abs/misc/lastErr && echo \$err1 > /etc/abs/misc/lastErr
+	exit 1
 fi
 echo "Oki! Preparing iso build using ${fgCyan}${archisoProfile}${txReset}!" && sleep 1.3
 read -p "Where do you want the outFolder to be? (Full path. Unfortunately ~/ expansion ${fgRed}doesn't${txReset} work) : " outDir
@@ -207,7 +218,7 @@ n | N | no | No | NO )
 	;;
 * )
 	if [[ $easterEgg != 3 ]]; then
-		echo "${fgRed}Invalid${txReset} response. ${txUnderline}Try again${txReset}."
+		echo "${fgRed}Invalid${txReset} response. ${txUnderline}Try again${txReset}. Either ${fgGreen}Yes${txReset} or ${fgRed}No${txReset}."
 		easterEgg=$(($easterEgg + 1))
 	else
 		echo "No ${txBold}way${txReset} you messed this up ${txBold}${fgRed}$easterEgg${txReset} times!" && sleep 1.7
@@ -240,10 +251,31 @@ echo "Build ${fgCyan}starts${txReset} in ${fgRed}5 seconds${txReset}!"
 echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
 sleep 5
 
-sudo mkarchiso -v -w $buildDir -o $outDir $profile
-sudo chown -R $user $buildDir
-sudo chown -R $user $outDir
-cp $buildDir/iso/arch/pkglist.x86_64.txt  $outDir/xerolinux-$(date +%Y.%m.%d)-pkglist.txt
+done="0"
+while [ done != 1 ]; do 
+read -p "Do you want to enable verbose out for mkarchiso? Is great for scanning for weird errors. (${fgGreen}y${txReset}/${fgRed}n${txReset}) " YN
+case $YN in
+	y | Y | yes | Yes | YES )
+		echo "Oki. Building iso ${fgCyan}with${txReset} verbose output!"
+		sudo mkarchiso -v -w $buildDir -o $outDir $profile
+		sudo chown -R $user $buildDir
+		sudo chown -R $user $outDir
+		cp $buildDir/iso/arch/pkglist.x86_64.txt  $outDir/xerolinux-$(date +%Y.%m.%d)-pkglist.txt
+		done="1"
+		;;
+	n | N | no | No | NO )
+		echo "Oki. Building iso ${fgCyan}without${txReset} verbose output!"
+		sudo mkarchiso -w $buildDir -o $outDir $profile
+		sudo chown -R $user $buildDir
+		sudo chown -R $user $outDir
+		cp $buildDir/iso/arch/pkglist.x86_64.txt  $outDir/xerolinux-$(date +%Y.%m.%d)-pkglist.txt
+		done="1"
+		;;
+	* )
+		echo "${fgRed}Invalid${txReset} response. ${txUnderline}Try again${txReset}. Either ${fgGreen}Yes${txReset} or ${fgRed}No${txReset}."
+		;;
+esac
+done
 
 echo $fgMagenta&&xUnicode 2730 49&&echo $txReset
 echo "${fgCyan}Done!${txReset} Look in ${txBold}${outFolder}${txReset} for your ${txUnderline}build and iso folder${txReset}!"
